# GitHub Actions CI/CD for D_Hotel_Direct
# This workflow builds the .NET solution and deploys to a VPS via FTP for Production environment.

name: CI/CD - Build and Deploy to VPS (Production)

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    env:
      ASPNETCORE_ENVIRONMENT: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # Manual approval before deployment
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: mduy26100, tunglvt
          minimum-approvals: 1
          issue-title: 'Production Deployment Approval'
          issue-body: 'Please approve this deployment to production.'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Backend/D_Hotel_Direct/src/WebAPI/WebAPI.csproj

      - name: Build
        run: dotnet build Backend/D_Hotel_Direct/src/WebAPI/WebAPI.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Backend/D_Hotel_Direct/src/WebAPI/WebAPI.csproj --configuration Release --output ./publish --no-build

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /
          timeout: 190000
          protocol: ftp
          security: loose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/publish/wwwroot/appsettings.*.json

      - name: Done
        run: echo "Deployment complete."
